[package]
name = "cwebp"
version = "0.1.0"
authors = ["vagrant"]
edition = "2018"

[dependencies]
bindgen = "0.47.0"
libwebp-sys = { path = "libwebp-sys" }

[workspace]
members = [
  "libwebp-sys",
]
default-members = [
  "libwebp-sys",
]
