cargo-features = ["profile-overrides"]

[package]
name = "imagers"
version = "0.1.0"
authors = ["vagrant"]
edition = "2018"

[dependencies]
bindgen = "0.48.1"
libwebp-sys = { path = "libwebp-sys" }
libjpeg-turbo-sys = { path = "libjpeg-turbo-sys" }
libpng-sys = { path = "libpng-sys" }
libc = "0.2.50"
lodepng = "2.4.2"
rgb = "0.8"

[dev-dependencies]
crc = "1.8.1"

[workspace]
members = [
  "libjpeg-turbo-sys",
  "libpng-sys",
  "libwebp-sys",
  "cwebp",
  "./"
]
default-members = [
  "libjpeg-turbo-sys",
  "libpng-sys",
  "libwebp-sys",
  "cwebp",
  "./"
]

[[test]]
name = "wali"
path = "tests/wali/mod.rs"

[profile.test]
opt-level = 3

[profile.bench]
opt-level = 3
incremental = true
overflow-checks = true

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
panic = 'unwind'
incremental = true
overflow-checks = false

[profile.release.overrides.libwebp-sys]
opt-level = 0
codegen-units = 1
incremental = true
overflow-checks = false
