[package]
name = "libjpeg-turbo-sys"
version = "0.1.0"
authors = ["Wangweizhen <wangweizhen@bilibili.com>"]
edition = "2018"
build = "build.rs"

[dependencies]

[build-dependencies]
bindgen = "0.47.0"
