[package]
name = "libwebp-sys"
version = "0.1.0"
authors = ["vagrant"]
edition = "2018"
build = "build.rs"

[dependencies]
libc = "0.2.48"
lodepng = "2.4.2"
rgb = "0.8"

[build-dependencies]
bindgen = "0.47.0"

