[package]
name = "cwebp"
version = "0.1.0"
authors = ["Wangweizhen <wangweizhen@bilibili.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
libwebp-sys = { path = "../libwebp-sys" }
imagers = { path = "../" }
rgb = "0.8"
libc = "0.2.54"

[lib]
name = "cwebp"

[[bin]]
name = "cwebp"